apps/testly_admin/lib/testly_admin_web/router.ex
defmodule TestlyAdminWeb.Router do
  use TestlyAdminWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    plug(Testly.Authenticator.InvalidateSessionPlug)
    plug(Testly.Authenticator.FetchUserPlug)
  end

  pipeline :ensure_auth do
    plug(TestlyAdminWeb.EnsureAuthenticated)
  end

  scope "/auth", TestlyAdminWeb do
    pipe_through :browser

    get "/signin", SessionController, :new
    post "/signin", SessionController, :create
    delete "/signout", SessionController, :delete
  end

  get("/health", TestlyAdminWeb.HealthController, :index)

  scope "/", TestlyAdminWeb do
    pipe_through([:browser, :ensure_auth])

    get("/", PageController, :index)
    resources("/projects", ProjectController)
    resources("/users", UserController)
    resources("/test_ideas", TestIdeaController)
    resources("/test_idea_categories", TestIdeaCategoryController)

    post("/users/:user_id/sign_in", UserController, :sign_in)
  end
end

apps/testly_admin/lib/testly_admin_web/views/layout_view.ex
defmodule TestlyAdminWeb.LayoutView do
  use TestlyAdminWeb, :view
end

apps/testly_admin/lib/testly_admin_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Testly Admin Dashboard</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
</head>
<body>
  <div class="wrapper">
    <nav class="sidebar">
      <div class="sidebar-content ">
        <a class="sidebar-brand" href="index.html">
          <img class="feather feather-box align-middle" src="<%= Routes.static_path(@conn, "/images/logo.svg") %>" alt="">
        </a>

        <ul class="sidebar-nav">
          <li class="sidebar-header">
            Main
          </li>
          <li class="sidebar-item <%= if(List.first(@conn.path_info) === nil, do: "active", else: "") %>">
            <a href="<%= Routes.page_path(@conn, :index) %>" class="sidebar-link">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-sliders align-middle"><line x1="4" y1="21" x2="4" y2="14"></line><line x1="4" y1="10" x2="4" y2="3"></line><line x1="12" y1="21" x2="12" y2="12"></line><line x1="12" y1="8" x2="12" y2="3"></line><line x1="20" y1="21" x2="20" y2="16"></line><line x1="20" y1="12" x2="20" y2="3"></line><line x1="1" y1="14" x2="7" y2="14"></line><line x1="9" y1="8" x2="15" y2="8"></line><line x1="17" y1="16" x2="23" y2="16"></line></svg> 
              <span class="align-middle">Dashboard</span>
            </a>
          </li>
          <li class="sidebar-item <%= if(List.first(@conn.path_info) === "users", do: "active", else: "") %>">
            <a href="<%= Routes.user_path(@conn, :index) %>" class="sidebar-link">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users align-middle"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
              <span class="align-middle">Users</span>
            </a>
          </li>
          <li class="sidebar-item <%= if(List.first(@conn.path_info) === "projects", do: "active", else: "") %>">
            <a href="<%= Routes.project_path(@conn, :index) %>" class="sidebar-link">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-clipboard align-middle mr-2"><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"></path><rect x="8" y="2" width="8" height="4" rx="1" ry="1"></rect></svg>
              <span class="align-middle">Projects</span>
            </a>
          </li>
          <li class="sidebar-item">
            <a href="#ideas" data-toggle="collapse" class="sidebar-link collapsed" aria-expanded="false">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-list align-middle mr-2"><line x1="8" y1="6" x2="21" y2="6"></line><line x1="8" y1="12" x2="21" y2="12"></line><line x1="8" y1="18" x2="21" y2="18"></line><line x1="3" y1="6" x2="3" y2="6"></line><line x1="3" y1="12" x2="3" y2="12"></line><line x1="3" y1="18" x2="3" y2="18"></line></svg>
              <span class="align-middle">Idea Lab</span>
            </a>

            <ul id="ideas" class="sidebar-dropdown list-unstyled collapse">
              <li class="sidebar-item <%= if(List.first(@conn.path_info) === "test_ideas", do: "active", else: "") %>">
                <%= link("Ideas", to: Routes.test_idea_path(@conn, :index), class: "sidebar-link ") %>
              </li>

              <li class="sidebar-item <%= if(List.first(@conn.path_info) === "test_idea_categories", do: "active", else: "") %>">
                <%= link("Categories", to: Routes.test_idea_category_path(@conn, :index), class: "sidebar-link") %>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>

    <div class="main">
      <nav class="navbar navbar-expand navbar-light bg-white">
				<a class="sidebar-toggle d-flex mr-2">
          <i class="hamburger align-self-center"></i>
        </a>

				<div class="navbar-collapse collapse">
					<ul class="navbar-nav ml-auto">
            <% current_user = @conn.assigns.current_account_user %>
        
						<li class="nav-item dropdown">
							<a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-toggle="dropdown">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-settings align-middle"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg>
              </a>

							<a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-toggle="dropdown">
                <img src="<%= Testly.Accounts.Avatar.url({current_user.avatar, current_user})%>" class="avatar img-fluid rounded-circle mr-1" alt="<%= current_user.full_name %>"> 
                <span class="text-dark"><%= current_user.full_name %></span>
              </a>
							<div class="dropdown-menu dropdown-menu-right">
                <%= link "Logout", to: "/auth/signout", method: :delete, class: "dropdown-item" %>
							</div>
						</li>
					</ul>
				</div>
			</nav>
      <main class="content">
        <div class="container-fluid p-0">
          <%= render @view_module, @view_template, assigns %>
        </div>
      </main>
    </div>
  </div>

  <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/app.js") %>'></script>
</body>
</html>