apps/testly_admin/lib/testly_admin_web/router.ex
defmodule TestlyAdminWeb.Router do
  use TestlyAdminWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    plug(Testly.Authenticator.InvalidateSessionPlug)
    plug(Testly.Authenticator.FetchUserPlug)
  end

  pipeline :ensure_auth do
    plug(TestlyAdminWeb.EnsureAuthenticated)
  end

  scope "/auth", TestlyAdminWeb do
    pipe_through :browser

    get "/signin", SessionController, :new
    post "/signin", SessionController, :create
    delete "/signout", SessionController, :delete
  end

  get("/health", TestlyAdminWeb.HealthController, :index)

  scope "/", TestlyAdminWeb do
    pipe_through([:browser, :ensure_auth])

    get("/", PageController, :index)
    resources("/projects", ProjectController)
    resources("/users", UserController)
    resources("/test_ideas", TestIdeaController)
    resources("/test_idea_categories", TestIdeaCategoryController)

    post("/users/:user_id/sign_in", UserController, :sign_in)
  end
end

apps/testly_admin/lib/testly_admin_web/controllers/session_controller.ex
defmodule TestlyAdminWeb.SessionController do
  use TestlyAdminWeb, :controller

  alias Testly.Accounts.SignInForm
  alias Testly.Accounts
  alias Testly.Authenticator.Session
  plug :put_layout, false

  @spec new(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def new(conn, _params) do
    changeset = Accounts.change_sign_in_form(%SignInForm{})
    render(conn, "new.html", changeset: changeset)
  end

  @spec create(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def create(conn, %{"sign_in_form" => params}) do
    case Accounts.sign_in_admin(params) do
      {:ok, form} ->
        user = Accounts.get_user_by_email(form.email)

        conn
        |> Session.sign_in(user.id, form.remember_me)
        |> redirect(to: "/")

      {:error, ch} ->
        render(conn, "new.html",
          changeset: %{ch | action: :validation_errors},
          header_inverted: true
        )
    end
  end

  @spec delete(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def delete(conn, _params) do
    conn
    |> Session.sign_out()
    |> redirect(to: "/auth/signin")
  end
end

apps/testly_admin/lib/testly_admin_web/views/session_view.ex
defmodule TestlyAdminWeb.SessionView do
  use TestlyAdminWeb, :view
end

apps/testly_admin/lib/testly_admin_web/templates/session/new.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Testly Admin - Sign In</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <style>
      html,
      body {
        height: 100%;
      }

      body {
        display: -ms-flexbox;
        display: flex;
        -ms-flex-align: center;
        align-items: center;
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
      }
      .form-signin .checkbox {
        font-weight: 400;
      }
      .form-signin .form-control {
        position: relative;
        box-sizing: border-box;
        height: auto;
        padding: 10px;
        font-size: 16px;
      }
      .form-signin .form-control:focus {
        z-index: 2;
      }
      .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
      }
      .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
      }

    </style> 
  </head>

  <body class="text-center">
    <%= form_for @changeset, Routes.session_path(@conn, :create), [class: "form-signin"], fn f -> %>
      <h1 class="h3 mb-3 font-weight-normal">Admin Panel</h1>

      <%= input(f, :email, label: false, input_opts: [placeholder: "Email"]) %>
      <%= input(f, :password, label: false, input_opts: [placeholder: "Password"]) %>

      <br/>

      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    <% end %>
  </body>
</html>